### ISSUE TITLE
ssd1306 - observed once: ENODEV   19  /* No such device */

### ISSUE THREAD

**Issue by aschuma** [aschuma/esp32_ssd1306_metaefa#30]
Observed once: (self healing, recovered itself) 
Problems occurred while refreshing UI

```
OSError: [Errno 19] ENODEV
Traceback (most recent call last):
  File "timer.py", line 15, in <lambda>
  File "main.py", line 85, in <lambda>
  File "main.py", line 42, in paint
  File "ssd1306.py", line 76, in invert
  File "ssd1306.py", line 104, in write_cmd
OSError: [Errno 19] ENODEV
Traceback (most recent call last):
  File "timer.py", line 15, in <lambda>
  File "main.py", line 85, in <lambda>
  File "main.py", line 42, in paint
  File "ssd1306.py", line 76, in invert
  File "ssd1306.py", line 104, in write_cmd
OSError: [Errno 19] ENODEV
...
```

`#define ENODEV      19  /* No such device */`

In addition the active rest service indicator is shown twice (now also on top of the screen)

**Comment by aschuma** [comment]
Closing... not observed anymore
